# Generated by `sudo nixos-hw-sync` on your actual machine.
# This file is host-specific by design — replace it after importing your own.
{ config, pkgs, ... }: {
  hardware.cpu.intel.updateMicrocode = true;
  nixpkgs.hostPlatform = "x86_64-linux";
}
